### ISSUE TITLE
404 on http://localhost:8080/scripts/app.js 

### ISSUE THREAD

**Issue by ylacaute** [NewDadaFE/generator-react-impression#1]
There is a problem with your port configuration. Port 8080 is your json-server.

Maybe you could update template for webpack.dev.config.js :
 - webpack-dev-server/client?http://localhost:8081

The readme should be updated too (8081 and not 8080)

**Comment by liufei** [comment]
No json-server here. Port 8080 is where your project running at.

If you want to proxy api request, edit webpack config [here](https://github.com/NewDadaFE/generator-react-impression/blob/master/app/templates/webpack.dev.config.js#L86). For example:
```js
proxy: {
  '/api': 'http://localhost:3000'
}
```

**Comment by ylacaute** [comment]
Sorry you right, it was my json-server which I forgot to stop :)
As your application have started I didn't notice that immediatly... and got a 404 error.
Now my json-server is turned off, everything is fine.
